/**
 * Type declaration for the WebAssembly module
 * The actual swisseph.js file is generated by build-wasm.sh
 */
declare module '../dist/swisseph.js' {
  export default function (): Promise<any>;
}
